version: "2"
services:
  app:
    container_name: app
    image: trustlab/ixo-elysian:latest
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://db:27017/elysian
      - MEMCACHE_URI=cache:11211
      - RABITMQ_URI=amqp://guest:guest@mq:5672
      - BLOCKCHAIN_URI_REST=http://34.201.48.61:1317/
      - BLOCKCHAIN_URI_TENDERMINT=http://34.201.48.61:46657/broadcast_tx_sync?tx=0x
      - CONFIG=/usr/src/app/bin/config.json
      - TEMPLATE_REPO=https://api.github.com/repos/ixofoundation/schema/contents/
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - db
      - cache
      - mq
      - pol
      - cli
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
      
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
      - ./backup:/backup
    ports:
      - "27017:27017"

  cache:
    container_name: cache
    image: memcached:latest
    ports:
      - "11211:11211"

  mq:
    container_name: mq
    image: rabbitmq:latest
    ports:
        - "5672:5672"
    restart: always

  pol:
    container_name: pol
    image: trustlab/ixo-pol
    environment:
      - RABITMQ_URI=amqp://guest:guest@mq:5672
      - BLOCKCHAIN_URI_TENDERMINT=http://35.192.187.110:46657/broadcast_tx_sync?tx=0x
      - POLLTIMER=3000
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"


  cli:
    container_name: cli
    image: trustlab/ixo-cli

