version: "2"
services:
  app:
    environment:
      - MONGODB_URI=mongodb://${USER}:${PASSWORD}@db:27017/elysian
      - BLOCKCHAIN_URI_REST=https://explorer.ixo.world/api/
      - ETHEREUM_API=https://mainnet.infura.io/
      - ASYM_CYPHER=${ASYMCYPHER}
      - ASYM_KEY=${ASYMKEY}
  db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOTPASS}
  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://blockchain.ixo.world:46657/broadcast_tx_sync?tx=0x

  cli:
    environment:
      - BLOCKCHAIN_URI_REST=https://explorer.ixo.world/api/did/getByDid/