version: "2"
services:
  app:
    environment:
      - BLOCKCHAIN_URI_REST=http://35.192.187.110:1317/
    build: .
    ports:
      - "5000:5000"
      
  db:
    ports:
      - "27017:27017"

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"

  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://35.192.187.110:46657/broadcast_tx_sync?tx=0x

