version: "2"
services:
  app:
    environment:
      - BLOCKCHAIN_URI_REST=https://explorer.ixo.world/api/
      - ETHEREUM_API=https://mainnet.infura.io/
      - ASYM_CYPHER=aes-256-cbc
      - ASYM_KEY=trustlab.tech
  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://blockchain.ixo.world:46657/broadcast_tx_sync?tx=0x

  cli:
    environment:
      - BLOCKCHAIN_URI_REST=https://explorer.ixo.world/api/did/getByDid/