version: "2"
services:
  app:
    environment:
      - BLOCKCHAIN_URI_REST=http://35.192.187.110:1317/
      - BLOCKCHAIN_URI_TENDERMINT=http://35.192.187.110:46657/broadcast_tx_sync?tx=0x

  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://35.192.187.110:46657/broadcast_tx_sync?tx=0x

