version: "2"
services:
  app:
    environment:
      - BLOCKCHAIN_URI_REST=http://beta.cosmos.ixo.world:1317/
    ports:
      - "443:5000"
      
  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://beta.cosmos.ixo.world:46657/broadcast_tx_sync?tx=0x

