version: "2"
services:
  app:
    environment:
      - BLOCKCHAIN_URI_REST=http://beta.cosmos.ixo.world:80/api/did/getByDid/
    build: .
  db:
    ports:
      - "27017:27017"

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"

  pol:
    environment:
      - BLOCKCHAIN_URI_TENDERMINT=http://beta.cosmos.ixo.world:46657/broadcast_tx_sync?tx=0x